repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        exclude: ^docs/mkdocs.yml$
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort

