apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-agent-github-app
  namespace: pr-agent
  labels:
    app: pr-agent-github-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pr-agent-github-app
  template:
    metadata:
      labels:
        app: pr-agent-github-app
    spec:
      containers:
      - name: pr-agent-github-app
        image: username/pr-agent:latest
        command: ["python", "-m", "pr_agent.servers.github_app"]
        ports:
        - containerPort: 8080
        env:
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: pr-agent-secrets
              key: github-app-id
        - name: GITHUB_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: pr-agent-secrets
              key: github-app-private-key
        - name: GITHUB_APP_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: pr-agent-secrets
              key: github-webhook-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: pr-agent-secrets
              key: openai-api-key
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pr-agent-github-app
  namespace: pr-agent
spec:
  selector:
    app: pr-agent-github-app
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pr-agent-github-app
  namespace: pr-agent
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - pr-agent.example.com
    secretName: pr-agent-tls
  rules:
  - host: pr-agent.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pr-agent-github-app
            port:
              number: 80
